### ISSUE TITLE
Show notification for user if installer is not running with elevated privileges

### ISSUE THREAD

**Issue by insertt** [panda-lang/installer#8]
We need to inform users that if installer is not running with elevated privileges, we can only install Panda binary as local installation and what it means in the end.

**Comment by wvffle** [comment]
Rather than notification I'd add a radio buttons to select whether user wants to install for himself or for everyone. Also that would require something like `canInstallGlobally` which returns `true`/`false` to determine if we can specify install path ourselves

**Edit**: Better yet, `hasAdminPriviledges` seems better name for me
